# Generated by Django 5.2.8 on 2025-11-16 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=255)),
                ('transaction_timestamp', models.DateTimeField()),
                ('card_id', models.BigIntegerField()),
                ('expiry_date', models.CharField(blank=True, max_length=50, null=True)),
                ('issuer_bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('merchant_id', models.BigIntegerField(blank=True, null=True)),
                ('merchant_mcc', models.BigIntegerField(blank=True, null=True)),
                ('mcc_category', models.CharField(blank=True, max_length=255, null=True)),
                ('merchant_city', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_type', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_amount_kzt', models.FloatField(blank=True, null=True)),
                ('original_amount', models.FloatField(blank=True, null=True)),
                ('transaction_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('acquirer_country_iso', models.CharField(blank=True, max_length=10, null=True)),
                ('pos_entry_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('wallet_type', models.CharField(blank=True, max_length=100, null=True)),
                ('index_level_0', models.BigIntegerField(blank=True, db_column='__index_level_0__', null=True)),
            ],
            options={
                'db_table': 'transaction',
                'ordering': ['-transaction_timestamp'],
            },
        ),
    ]
